### ISSUE TITLE
Mobile tethering broken.

### ISSUE THREAD

**Issue by RealSlimShadyMC** [Android-L-Porting-Team/Android-L-Mako#29] opened 2014-07-08 16:23 UTC
I can start the tethering deamon and it broadcasts, but packets don't get routed through my phone, and instead get stuck.

**Comment by Darex2094** [comment] 2014-07-08 16:34
This is a duplicate of #11

**Comment by RealSlimShadyMC** [comment] 2014-07-08 16:54
Is the LTE patch built into the ROM? I'm just using the normal radio

**Comment by Darex2094** [comment] 2014-07-08 16:56
It isn't necessarily a problem with LTE as much as it's a routing and tunneling issue. It affects tethering, VPN tunneling, etc.

**Comment by benpye** [comment] 2014-07-08 17:51
Closed as duplicate of #11 .

**Closed as completed by benpye** 2014-07-08 17:51 UTC
Labels: duplicate
