### ISSUE TITLE
Google Now Hotword detection doesn't work.

### ISSUE THREAD

**Issue by Boggartfly** [Android-L-Porting-Team/Android-L-Mako#38] opened 2014-07-09 03:41 UTC
I've tried each and every combo of language but hotword detection refuses to work. Can you please look into this guys? I love your work. It's awesome!

**Comment by ConnorBaker** [comment] 2014-07-09 04:13
Enable audio history (image one) and all the toggles in image two.
![screenshot_2014-07-09-00-09-29](https://cloud.githubusercontent.com/assets/3880346/3519777/0e793186-071f-11e4-990b-3e8616dd32ad.png)

![screenshot_2014-07-09-00-09-24](https://cloud.githubusercontent.com/assets/3880346/3519783/3b945858-071f-11e4-830b-bb5675970339.png)

Warm regards,
- Connor Baker

**Comment by Boggartfly** [comment] 2014-07-09 04:25
I did all your steps. The phone just refuses to understand no matter what i'm doing. I've tried imitating a half a dozen accents. I don't know whether this will work but it will make me a actor, a funny one at that!

**Comment by senthilrameshjv** [comment] 2014-07-09 05:28
Happens with me also. I have the Hotword detection on in Google search app. I use Google launcher. No matter how much i scream, it doesn't detect it.

**Comment by lazarovidiu** [comment] 2014-07-09 09:58
It seems to be an issue with the English US language speak detection. When set to English US and I manually tap the microphone icon and say ok google it writes "okay Google". If I set it to English UK it writes "OK Google". They seem to be reversed I think.

**Comment by Boggartfly** [comment] 2014-07-09 10:13
Well manual detection is working. Anything else?

**Comment by beinghuman23** [comment] 2014-07-09 10:30
I too reported the same issue...day before.
thing is that its a language pack issue (English US)....i just changed the language to 'English India' and its working....

**Comment by lazarovidiu** [comment] 2014-07-09 10:32
But "OK Google" works on any screen for Eglish US only.

**Comment by beinghuman23** [comment] 2014-07-09 10:40
But here its not working even in google search app..

**Comment by Darex2094** [comment] 2014-07-09 14:48
This is a duplicate of https://github.com/Android-L-Porting-Team/Android-L-Mako/issues/30

@percy-g2 , where ya at with the quick close and 'it's an L problem'?

**Comment by percy-g2** [comment] 2014-07-09 14:52
https://code.google.com/p/android-developer-preview/issues/detail?id=265&can=1&q=hotword&colspec=ID%20Type%20Status%20Owner%20Summary

**Closed as completed by percy-g2** 2014-07-09 14:52 UTC
