### ISSUE TITLE
USB Tethering broken

### ISSUE THREAD

**Issue by JustBuddy** [Android-L-Porting-Team/Android-L-Mako#54] opened 2014-07-10 08:01 UTC
Im coming from cm11, but performed a clean install (wipe everything). I really rely on USB Tethering, but it isnt working. Network Adapter loads, but i don't get a signal.

**Comment by benpye** [comment] 2014-07-10 09:36
Closed as duplicate of #11.

**Closed as completed by benpye** 2014-07-10 09:36 UTC
